### ISSUE TITLE
Update date

### ISSUE THREAD

**Issue by chtiland** [dploeger/dokuwiki-plugin-lastmod#6]
Hello !
Can you update date in plugin.info.txt in order to have the same last modification date as on https://www.dokuwiki.org/plugin:lastmod ?
Thus, this plugin won't be listed as "updatable".

Thanks

**Comment by dploeger** [comment]
Done. Thanks for reporting.

**Comment by chtiland** [comment]
Thank for correction, but download link on https://www.dokuwiki.org/plugin:lastmod refers to archive/v1.1.zip and file in this archive are not updated with master.
So I changed the download link on dokuwiki.org to the master.zip.
